sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678
  redis:
    host: 172.24.109.56
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wx99913d7f8f93b167
    secret: 4176954dfa264fce23497c98da47bb7d
